import type { ReactComponentBuildConfig, WebComponentBuildConfig } from "../../tasks/build/builder/src/types.ts";

export const webComponentList: WebComponentBuildConfig[] = [
  {
    name: "jb-tab-trigger",
    path: "./trigger/web-component/lib/index.ts",
    outputPath: "./trigger/web-component/dist/index.js",
    tsConfigPath: "./trigger/web-component/tsconfig.json",
    external: ["jb-core", "jb-core/theme"],
    globals: { "jb-core": "JBCore", "jb-core/theme": "JBCoreTheme" },
    umdName: "JBTabTrigger",
    dir: "./trigger",
  },
  {
    name: "jb-tab-content",
    path: "./content/web-component/lib/index.ts",
    outputPath: "./content/web-component/dist/index.js",
    tsConfigPath: "./content/web-component/tsconfig.json",
    external: ["jb-core"],
    globals: { "jb-core": "JBCore" },
    umdName: "JBTabContent",
    dir: "./content",
  },
  {
    name: "jb-tab-list",
    path: "./list/web-component/lib/index.ts",
    outputPath: "./list/web-component/dist/index.js",
    tsConfigPath: "./list/web-component/tsconfig.json",
    external: ["jb-core", "jb-core/theme", "jb-tab/trigger"],
    globals: { "jb-core": "JBCore", "jb-core/theme": "JBCoreTheme", "jb-tab/trigger": "JBTabTrigger" },
    umdName: "JBTabList",
    dir: "./list",
  },
  {
    name: "jb-tab",
    path: "./web-component/lib/index.ts",
    outputPath: "./web-component/dist/index.js",
    tsConfigPath: "./web-component/tsconfig.json",
    external: ["jb-core", "jb-tab/list", "jb-tab/trigger", "jb-tab/content"],
    globals: {
      "jb-core": "JBCore",
      "jb-tab/list": "JBTabList",
      "jb-tab/trigger": "JBTabTrigger",
      "jb-tab/content": "JBTabContent",
    },
    umdName: "JBTab",
  },
];

export const reactComponentList: ReactComponentBuildConfig[] = [
  {
    name: "jb-tab-trigger-react",
    path: "./trigger/react/lib/index.tsx",
    outputPath: "./trigger/react/dist/index.js",
    tsConfigPath: "./trigger/react/tsconfig.json",
    external: ["react", "jb-core/react", "jb-tab/trigger"],
    globals: { react: "React", "jb-core/react": "JBCoreReact", "jb-tab/trigger": "JBTabTrigger" },
    umdName: "JBTabTriggerReact",
    dir: "./trigger/react",
  },
  {
    name: "jb-tab-content-react",
    path: "./content/react/lib/index.tsx",
    outputPath: "./content/react/dist/index.js",
    tsConfigPath: "./content/react/tsconfig.json",
    external: ["react", "jb-core/react", "jb-tab/content"],
    globals: { react: "React", "jb-core/react": "JBCoreReact", "jb-tab/content": "JBTabContent" },
    umdName: "JBTabContentReact",
    dir: "./content/react",
  },
  {
    name: "jb-tab-list-react",
    path: "./list/react/lib/index.tsx",
    outputPath: "./list/react/dist/index.js",
    tsConfigPath: "./list/react/tsconfig.json",
    external: ["react", "jb-core/react", "jb-tab/list"],
    globals: { react: "React", "jb-core/react": "JBCoreReact", "jb-tab/list": "JBTabList" },
    umdName: "JBTabListReact",
    dir: "./list/react",
  },
  {
    name: "jb-tab-react",
    path: "./react/lib/index.tsx",
    outputPath: "./react/dist/index.js",
    tsConfigPath: "./react/tsconfig.json",
    external: ["react", "jb-core/react", "jb-tab"],
    globals: { react: "React", "jb-core/react": "JBCoreReact", "jb-tab": "JBTab" },
    umdName: "JBTabReact",
    dir: "./react",
  },
];
